# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 00:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limitesCommunes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefectures',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=2154),
        ),
    ]
